### ISSUE TITLE
Cannot start a fresh install of Phenomic

### ISSUE THREAD

**Issue by djorak** [MoOx/phenomic#1011]
Whenever I reach the start step (`npm start` or `yarn start`) I get an error regarding the webpack file:

```javascript
> phenomic start

ℹ Phenomic is starting +0.2s
/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/mazej01/Workspace/_julien/julien-maze.com/webpack.config.js: Unexpected token (26:4)
  24 |
  25 |   return {
> 26 |     ...config.dev && {
     |     ^
  27 |       devtool: "#cheap-module-eval-source-map",
  28 |     },
  29 |     module: {
    at Parser.pp$5.raise (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:4443:13)
    at Parser.pp.unexpected (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:1755:8)
    at Parser.pp$3.parseIdentifier (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:4321:10)
    at Parser.pp$3.parsePropertyName (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:4145:96)
    at Parser.pp$3.parseObj (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:4035:12)
    at Parser.pp$3.parseExprAtom (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:3709:19)
    at Parser.pp$3.parseExprSubscripts (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:3484:19)
    at Parser.pp$3.parseMaybeUnary (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:3464:19)
    at Parser.pp$3.parseExprOps (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:3394:19)
    at Parser.pp$3.parseMaybeConditional (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:3371:19)
    at Parser.pp$3.parseMaybeAssign (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:3334:19)
    at Parser.pp$3.parseExpression (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:3296:19)
    at Parser.pp$1.parseReturnStatement (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:2072:26)
    at Parser.pp$1.parseStatement (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:1842:19)
    at Parser.pp$1.parseBlockBody (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:2262:21)
    at Parser.pp$1.parseBlock (/Users/mazej01/Workspace/_julien/julien-maze.com/node_modules/babylon/lib/index.js:2241:8)
```

This is on a mac using:
- **OS X 10.11.6**
- **Node v6.10.0** or **v4.4.7**
- **NPM 3.10.10** or **yarn 0.23.4**

I always get the same error. Here are the commands I've used:
```
mkdir my-website && cd my-website
yarn add phenomic && ./node_modules/.bin/phenomic setup
yarn install
yarn start
```
```
mkdir my-website && cd my-website
npm install phenomic && ./node_modules/.bin/phenomic setup
npm i
npm start
```

I've followed the docs to the letter, am I doing anything wrong or is there something wrong with the babel config?

**Comment by MoOx** [comment]
Probably a missing babel transfo (object spread operator) try switching to stage-2 or stage-1?

**Comment by djorak** [comment]
I found the issue, my `NODE_ENV` was set to `dev` rather than `development` (we use `dev` in our team) which meant that babel was not using any of the config from `package.json`.

`NODE_ENV=development npm start` worked perfectly.

Thanks for the help. :)
