### ISSUE TITLE
(react-helmet update) TypeError: Cannot read property 'toComponent' of undefined

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#437]
This happen if you update phenomic but forget to update react-helmet. **We should show an explicit warning.**

```
/Users/MoOx/Sync/Development/putaindecode.io/node_modules/phenomic/lib/static/index.js:13
      throw error;
      ^

TypeError: Cannot read property 'toComponent' of undefined
    at /Users/MoOx/Sync/Development/putaindecode.io/node_modules/phenomic/lib/static/to-html/url-as-html.js:74:31
    at /Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/match.js:65:5
    at /Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/createTransitionManager.js:117:11
    at done (/Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/AsyncUtils.js:81:19)
    at /Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/AsyncUtils.js:87:7
    at getComponentsForRoute (/Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/getComponents.js:9:5)
    at /Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/getComponents.js:28:5
    at /Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/AsyncUtils.js:86:5
    at Array.forEach (native)
    at Object.mapAsync (/Users/MoOx/Sync/Development/putaindecode.io/node_modules/react-router/lib/AsyncUtils.js:85:9)
```

**Comment by MoOx** [comment]
I guess it's ok know. Anyway if someone is stuck on this and read this page, please get in touch ;)
