### ISSUE TITLE
Error in dev mode with highlight.js autoit language

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/phenomic#616]
Reproduce: 

- Clone this repo
- `npm install && npm run docs start`
- Output: 

```
ERROR in ./~/highlight.js/lib/languages/autoit.js
Module parse failed: /home/khoa/web/phenomic/docs/node_modules/highlight.js/lib/languages/autoit.js Maximum call stack size exceeded
You may need an appropriate loader to handle this file type.
RangeError: Maximum call stack size exceeded
    at Parser.applyPluginsBailResult (/home/khoa/web/phenomic/node_modules/tapable/lib/Tapable.js:44:35)
    at Parser.evaluateExpression (/home/khoa/web/phenomic/node_modules/webpack/lib/Parser.js:787:20)
    at Parser.<anonymous> (/home/khoa/web/phenomic/node_modules/webpack/lib/Parser.js:66:16)
    at Parser.applyPluginsBailResult (/home/khoa/web/phenomic/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/khoa/web/phenomic/node_modules/webpack/lib/Parser.js:787:20)
    at Parser.<anonymous> (/home/khoa/web/phenomic/node_modules/webpack/lib/Parser.js:66:16)
    at Parser.applyPluginsBailResult (/home/khoa/web/phenomic/node_modules/tapable/lib/Tapable.js:48:50)
    at Parser.evaluateExpression (/home/khoa/web/phenomic/node_modules/webpack/lib/Parser.js:787:20)
    at Parser.<anonymous> (/home/khoa/web/phenomic/node_modules/webpack/lib/Parser.js:66:16)
    at Parser.applyPluginsBailResult (/home/khoa/web/phenomic/node_modules/tapable/lib/Tapable.js:48:50)
 @ ./~/highlight.js/lib/index.js 13:32-61
```

A hacky fix: https://github.com/shprink/wordpress-hybrid-client/issues/103
Issue from highlight.js : https://github.com/isagalaev/highlight.js/issues/895

That issue said that this was fixed in version 9.4.0 to somehow on 9.6.0 this error comebacks

**Comment by thangngoc89** [comment]
By locking the highlight.js version to 9.4.0 resolves this issue. So this is a upstream issue.

**Comment by thangngoc89** [comment]
@MoOx ping. Do you think we should handle in Phenomic ? It's a day and no response from @-isagalaev.

**Comment by MoOx** [comment]
I have a local wip and want to finish #15. Will check later before cutting a release.

**Comment by thangngoc89** [comment]
Ok. Thanks

**Comment by MoOx** [comment]
Just got the issue. But hey!

```
cat /Users/moox/Sync/Development/phenomic/docs/node_modules/highlight.js/package.json|grep version
  "version": "8.9.1"
```

**Comment by MoOx** [comment]
I updated some remark packages, should fix the thing.

**Comment by thangngoc89** [comment]
You should have typed 

npm ls highlight.js

Will confirm this later

**Comment by MoOx** [comment]
I found the path from the webpack error, it's that simple.
But indeed, it seems there is a fuck:

├─┬ remark-highlight.js@3.1.1 invalid
│ └── highlight.js@9.6.0 

So we currently have 2 versions, that's what is probably causing the issue.

**Comment by thangngoc89** [comment]
This is weird. If there is 2 highlight.js npm should have told us.

**Comment by MoOx** [comment]
Why?

**Comment by thangngoc89** [comment]
The npm ls command willl tell us about all instance of hightlight.js.  that have beenn installled

**Comment by MoOx** [comment]
I have found the issue. It's hardcoded in docs/package.json deps. That's a mess.

**Comment by thangngoc89** [comment]
@MoOx I don't see this anymore. Was it resolved itself ?

**Comment by MoOx** [comment]
Not really. @ben-eb handled this.

https://github.com/wooorm/lowlight/issues/2
