### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by MoOx** [MoOx/phenomic#648]
From https://travis-ci.org/putaindecode/putaindecode.io/builds/154302582#L1616

```
> putaindecode.io@ build /home/travis/build/putaindecode/putaindecode.io

> phenomic build

  phenomic:builder ✓ Static build: assets copy completed +0ms

  phenomic:builder ✓ Static build: client build completed +38s

  phenomic:builder ✓ Static build: static build completed +3s

  phenomic:static ✗ Static build failed +6s

/home/travis/build/putaindecode/putaindecode.io/node_modules/phenomic/lib/static/index.js:13

      throw error;

      ^

TypeError: Cannot read property 'trim' of undefined

    at new ReadingTime (eval at <anonymous> (/home/travis/build/putaindecode/putaindecode.io/node_modules/.cache/phenomic/phenomic.node.bundle.js:449:2), <anonymous>:33:33)

    at [object Object].ReactCompositeComponentMixin._constructComponentWithoutOwner (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactCompositeComponent.js:296:27)

    at [object Object].ReactCompositeComponentMixin._constructComponent (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactCompositeComponent.js:283:19)

    at [object Object].ReactCompositeComponentMixin.mountComponent (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactCompositeComponent.js:190:21)

    at Object.ReactReconciler.mountComponent (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactReconciler.js:47:35)

    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactMultiChild.js:240:44)

    at ReactDOMComponent.Mixin._createContentMarkup (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactDOMComponent.js:660:32)

    at ReactDOMComponent.Mixin.mountComponent (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactDOMComponent.js:527:29)

    at Object.ReactReconciler.mountComponent (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactReconciler.js:47:35)

    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/travis/build/putaindecode/putaindecode.io/node_modules/react/lib/ReactMultiChild.js:240:44)
```

**Comment by MoOx** [comment]
Not a phenomic bug.
