### ISSUE TITLE
docs-start failed to run.

### ISSUE THREAD

**Issue by kevin940726** [MoOx/phenomic#727]
Enviroment:
* node v6.0.0
* npm v3.9.5

Steps to reproduce the bug:
* clone the master
* npm install
* npm run docs-start

Error output:
```
> phenomic@0.16.2 predocs-start /Users/Kai/Work/SideProjects/phenomic
> npm -s run docs

/Users/Kai/Work/SideProjects/phenomic/docs/node_modules/phenomic/lib/index.js:8
export { default as PageContainer } from "./components/PageContainer"
^^^^^^
SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Kai/Work/SideProjects/phenomic/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Kai/Work/SideProjects/phenomic/docs/webpack.config.babel.js:5:1)
    at Module._compile (module.js:541:32)
    at loader (/Users/Kai/Work/SideProjects/phenomic/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Kai/Work/SideProjects/phenomic/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

/Users/Kai/Work/SideProjects/phenomic/scripts/utils/test-folder.js:118
              throw _context.t0;
              ^
CommandError
    at ChildProcess.spawnOnClose (/Users/Kai/Work/SideProjects/phenomic/node_modules/async-exec-cmd/index.js:149:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

Is this [line](https://github.com/MoOx/phenomic/blob/master/scripts/docs.js#L3) meant to create symlink for the `node_modules`? Why we linked from `src` instead of `lib`?

**Comment by MoOx** [comment]
This is to be able to hot load update from src when working on docs :D
I may have introduced a regression recently, will take a look asap.

**Comment by thangngoc89** [comment]
I can't re-produce this. Which OS are you running ?

**Comment by kevin940726** [comment]
Mac OS X El Capitan 10.11.6

I'm gonna try to do some test again to figure out if this is only my mistake again 😰 .

**Comment by MoOx** [comment]
This line is supposed to handle the transformation... https://github.com/MoOx/phenomic/blob/30aaca23b971995432f6ed579cc564525f2ac637/docs/webpack.config.babel.js#L48
Not sure why this does not work for you...

**Comment by kevin940726** [comment]
Just cleaned the npm cache and it suddenly works... I am just going to close it as I cannot re-produce the bug anymore and it is most likely not a bug of this project at all.
