### ISSUE TITLE
"window is not defined [ truncated stack ]" error on Static build

### ISSUE THREAD

**Issue by DavidWells** [MoOx/phenomic#819]
Running into an error on serverside rendering. It's a problem somewhere in my code with a `window` call but the stack trace is showing `[ truncated stack ]`, so tracking this bastard down is proving to be a challenge.

Is this something via phenomic or is this something jacked up in my terminal? =)

![image](https://cloud.githubusercontent.com/assets/532272/19285951/e7593a7a-8fb0-11e6-9603-66f2f68d5c2a.png)

**Comment by MoOx** [comment]
Currently, [truncated stack] should be node internal stack (so really not important) https://github.com/MoOx/phenomic/blob/fb68a13a0e5c5981a38f7a07273f86e6e8cac4d6/src/_utils/error-formatter/__tests__/index.js#L26-L31

Can you try to open `node_modules/phenomic/lib/_utils/error-formatter/index.js` and comment this equivalent lines https://github.com/MoOx/phenomic/blob/fb68a13a0e5c5981a38f7a07273f86e6e8cac4d6/src/_utils/error-formatter/index.js#L28-L31 ?

**Comment by DavidWells** [comment]
Fixed my problem. I did it the hard way though =P

Just wanted to bring this up if it was phenomic swallowing the trace

**Comment by MoOx** [comment]
Maybe this should be more clear tho.

**Comment by DavidWells** [comment]
@MoOx PS launched our blog https://serverless.com/blog/ on the phenomic site. Bye bye wordpress =)

**Comment by mjisican** [comment]
I also came across this error while trying to deploy on github pages. i've recently configured snapsvg on my phenomic project. how do i fix this, i'm a starter, so i currently have no idea how to fix this.
 
![screen shot 2016-10-19 at 9 34 22 pm](https://cloud.githubusercontent.com/assets/12537930/19520774/f5e405f4-9643-11e6-83d5-3c96ceffbf4a.png)

**Comment by MoOx** [comment]
Truncated stack won't help you, really. It's just internal node stack.

So you "just" need to not import this module if window is missing. Your module is made to be executed in a browser, and so should not be imported if window does not exist (and it does not for the static rendering, via node).

**Comment by MoOx** [comment]
That said, I could catch "window is not defined" error and show a clear warning.

**Comment by mjisican** [comment]
i didn't read your previous suggestions to DavidWells, i will try those line of codes. Thanks for your fast reply :D

**Comment by mjisican** [comment]
been busy lately, this fixed my issue
```javascript
// removed import
...
export default class MyClass extends React.Component {
    ...
    componentDidMount() {
        const MyWindowDependentLibrary = require( 'path/to/library' );
        MyWindowDependentLibrary.doWork();
    }
    ...
}
```

this is another way

```javascript
const isBrowser = typeof window !== 'undefined';
const MyWindowDependentLibrary = isBrowser ? require( 'path/to/library') : undefined;
```

**Comment by DavidWells** [comment]
Just ran into this again. I know what is causing my issue. 

BUT mere mortals will see this and say WTF. =P

![image](https://cloud.githubusercontent.com/assets/532272/19782610/67586158-9c43-11e6-8019-af81e8065208.png)

How can we not truncate the stack? Maybe we write the error to file?

**Comment by montogeek** [comment]
@DavidWells What is causing this kind of errors?

**Comment by DavidWells** [comment]
@montogeek In my case here, it's including a clipboard lib for a handy lil copy component https://github.com/serverless/site/blob/addMeetupPages/src/components/Copy/Copy.js#L2

If I wrap in a `typeof window !== 'undefined'` it gets fixed. 

But basically any call to window, document, etc will cause a super vague error like this when `phenomic build` runs and it's not clear how to fix because the stack error is trucated

**Comment by MoOx** [comment]
I am thinking about adding a global jsdom instance before doing the static rendering to this what this can handle. Might be a good idea to try this.

If someone is curious about this idea, please let me know, this might make things better than a brutal error, even if we provide a good error message. This could make things works out of the box in most case.

**Comment by DavidWells** [comment]
Perhaps this lib: https://github.com/IndigoUnited/node-pretty-inspect might help?

**Comment by MoOx** [comment]
How this lib can help? Not sure what we should inspect here.

**Comment by arlair** [comment]
In my case the truncated stack trace was useful as it showed where in my code the exception was originating from while trying to create a static build.

In case it helps others, I changed `node_modules/phenomic/lib/builder/webpack/index.js` to console.log the caught exception:

```
      }).catch(function (err) {
        console.log(err)
        // (0, _log2.default)(_chalk2.default.red("Build failed"), "error");
        // setTimeout(function () {
        //   throw (0, _errorFormatter2.default)(err);
        // }, 1);
      });
```

**Comment by MoOx** [comment]
Can you show me the exact truncated stack? It should not remove useful informations.

**Comment by arlair** [comment]
```
ReferenceError: firebase is not defined
    at Object.module.exports.exports.isClient (/mypath/.cache/phenomic/webpack-node-build/webpack:/~/firebase/firebase.js:31:1)
    at __webpack_require__ (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:19:1)
    at Object.module.exports.k (/mypath/.cache/phenomic/webpack-node-build/webpack:/~/firebase/firebase-browser.js:8:1)
    at __webpack_require__ (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:19:1)
    at Object.<anonymous> (/mypath/.cache/phenomic/webpack-node-build/webpack:/finx/lib/firebase/index.js:1:1)
    at __webpack_require__ (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:19:1)
    at Object.<anonymous> (/mypath/.cache/phenomic/webpack-node-build/webpack:/finx/lib/firebase/stores/FirebaseStore.js:12:1)
    at __webpack_require__ (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:19:1)
    at Object.module.exports.c (/mypath/.cache/phenomic/webpack-node-build/webpack:/src/travel/stores.js:5:1)
    at __webpack_require__ (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:19:1)
    at Object.module.exports.module.exports.private (/mypath/.cache/phenomic/webpack-node-build/webpack:/src/metadata.js:3:1)
    at __webpack_require__ (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:19:1)
    at Object.module.exports.Object.defineProperty.value (/mypath/.cache/phenomic/webpack-node-build/webpack:/scripts/phenomic.node.js:3:1)
    at __webpack_require__ (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:19:1)
    at module.exports.Object.assign.i (/mypath/.cache/phenomic/webpack-node-build/webpack:/webpack/bootstrap bac9bec32862a3081f90:39:1)
    at Object.<anonymous> (/mypath/.cache/phenomic/webpack-node-build/phenomic.node.bundle.js:45:10)
```

**Comment by MoOx** [comment]
Thanks. This paths should not be removed, will fix that.

**Comment by MoOx** [comment]
0.20.3 will not truncated stack anymore (just clean paths a little) and will add an explanation for message with "XXX is undefined" with examples.

**Comment by MoOx** [comment]
Here is how it looks now (in #951).

![screen shot 2017-01-28 at 22 33 01](https://cloud.githubusercontent.com/assets/157534/22399997/e533f2e0-e5a9-11e6-8329-254debe6298a.png)

Is this better?
