### ISSUE TITLE
`npm start` fails without `chokidar` installed when using yarn

### ISSUE THREAD

**Issue by daaain** [MoOx/phenomic#869]
I've just done a fresh install following the setup guide from the docs: https://phenomic.io/docs/setup/

But on running `npm start` the server crashed as it was missing `chokidar` (see output below).

Manually adding it to `package.json` as dependency fixed the problem.

Are you assuming that `chokidar` is installed globally or did I miss something?

Can submit a PR in if you want!

```
ℹ Phenomic is starting +0.32s
✔ Development server listening on http://0.0.0.0:3333/ +1.52s
✔ Updated (in 8.38s)module.js:457
    throw err;
    ^

Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dain/workspace/games-website-refresh/node_modules/watchpack/lib/DirectoryWatcher.js:7:16)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dain/workspace/games-website-refresh/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at WatcherManager.getDirectoryWatcher (/Users/dain/workspace/games-website-refresh/node_modules/watchpack/lib/watcherManager.js:12:25)
    at WatcherManager.watchFile (/Users/dain/workspace/games-website-refresh/node_modules/watchpack/lib/watcherManager.js:26:14)
    at EventEmitter.<anonymous> (/Users/dain/workspace/games-website-refresh/node_modules/watchpack/lib/watchpack.js:34:49)
```

**Comment by MoOx** [comment]
Hi. This is not supposed to happen. I guess your initial npm install didn't do its work properly.
Our current tests verify that the dev server starts correctly without failure.
Are you using node 4+ and npm3+?

**Comment by daaain** [comment]
Hmm, this is what I have so it should have been all right:

```
> npm -v
3.10.9
> node -v
v6.4.0
```

I intentionally don't have pretty much anything installed globally, other than `node-gyp`, `npm` and `yarn`.

I looked through the logs, but nothing special, the errors and warnings are all expected during `npm install phenomic` I think:
 * `npm WARN addRemoteGit Error: Command failed: git config --get remote.origin.url`
 * some `UNMET PEER DEPENDENCY`
 * `npm WARN enoent ENOENT: no such file or directory, open '.../package.json'`

And then `yarn` ran without any problem:

```
> yarn
yarn install v0.15.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 71.56s.
```

So in the end I had to `yarn add chokidar --dev` and now it's fine.

**Comment by MoOx** [comment]
Have you used yarn to install phenomic?

**Comment by daaain** [comment]
No, I wasn't bold enough :) But maybe then the problem is mixing NPM and Yarn?

**Comment by MoOx** [comment]
Did you try a new clean install? I cannot reproduce.

**Comment by daaain** [comment]
Right, I spent some time experimenting with this using Docker, and the conclusion is that Yarn is messing something up. I don't have more time to find out exactly what's going on, but basically doing `npm install phenomic` and then `npm install` works, while `yarn add phenomic` and then `yarn` doesn't.

Also, chokidar comes as a dependency to babel-cli, so it really should be there without explicitly being added as a dependency, so the issue doesn't seem to be with Phenomic.

I'm pasting the Dockerfile below for reference (or if anyone wants to take this further), but as far as I'm concerned that issue can be closed.

Maybe it would be worthwhile calling out in the setup docs that it might not work with Yarn?

```
FROM node:6

MAINTAINER Daniel Demmel <dain@ustwo.com>

ENV NODE_ENV=development

RUN mkdir -p /usr/local/src/node_modules
WORKDIR /usr/local/src

# RUN npm install yarn -g

# RUN yarn add phenomic
RUN npm install phenomic
RUN ./node_modules/.bin/phenomic setup --test
# RUN yarn
RUN npm install

EXPOSE 3333

CMD ["npm", "start"]
```

**Comment by daaain** [comment]
Closing after referencing it from #818.

**Comment by MoOx** [comment]
So you need yarn 0.16.1 and whether use yarn for installing everything or npm and stick to it. Mixing npm install + yarn is not very good. I all tests working with yarn 0.16+
