### ISSUE TITLE
Installing first time via docs instructions, `yarn install` fails

### ISSUE THREAD

**Issue by alex-wilmer** [MoOx/phenomic#911]
```
awilmer@olm-awilmer torontojs.com (phenomic)*$ ./node_modules/.bin/phenomic setup
ℹ Note: All values can be adjusted later.
? Dashed name of your project (eg: my-project) torontojs
? Website url (eg: http://abc.xyz/) http://torontojs.com
? Repository url (eg: https://github.com/MoOx/phenomic.git, optional)

? Twitter nickname (eg: MoOx, optional)
? Do you want a CNAME file (eg: for GitHub Pages)? No
ℹ `package.json` generated
ℹ Base theme installed
✔ Project ready. Only one `npm install` and you are good to go!
awilmer@olm-awilmer torontojs.com (phenomic)*$ yarn install
yarn install v0.17.6
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[2/2] ⠠ phenomic
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
error /Users/awilmer/OpenSource/torontojs.com/node_modules/phenomic: Command failed.
Exit code: 1
Command: sh
Arguments: -c node npm/postinstall.js
Directory: /Users/awilmer/OpenSource/torontojs.com/node_modules/phenomic
Output:
/Users/awilmer/OpenSource/torontojs.com/node_modules/phenomic/npm/postinstall.js:64
        throw new Error(
        ^

Error: Cannot rename .npmignore to .gitignore in phenomic-theme-base
    at /Users/awilmer/OpenSource/torontojs.com/node_modules/phenomic/npm/postinstall.js:64:15
    at /Users/awilmer/OpenSource/torontojs.com/node_modules/fs-extra/lib/move/index.js:73:11
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by MoOx** [comment]
Thanks for reporting this. Looks like a bug for a [specific npm thing](https://github.com/MoOx/phenomic/blob/7a242d96ba3b1dbc88a2f5abef41c2550eac5bcf/npm/postinstall.js#L117-L133).

**Comment by raygesualdo** [comment]
It seems the `fs.move` callback doesn't gracefully handle `.gitignore` already being present. I'm about to fire off a PR with a proposed fix.
