### ISSUE TITLE
Assistance with setting up Jest snapshot tests

### ISSUE THREAD

**Issue by Strainy** [MoOx/phenomic#947]
Has anyone set up snapshot testing with Jest on a Phenomic site?

I'm trying to set up a basic test and it appears that when I use the `Link` component from the phenomic module it causes the test to fail:

```sh
> jest

 FAIL  src/fragments/HomePageWelcome/__tests__/HomePageWelcome.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'replace' of undefined

      at Object.<anonymous> (node_modules/phenomic/lib/client/index.js:44:47)
      at Object.<anonymous> (node_modules/phenomic/lib/components/PageContainer/component.js:27:15)
      at Object.<anonymous> (node_modules/phenomic/lib/components/PageContainer/index.js:13:18)
      at Object.<anonymous> (node_modules/phenomic/lib/index.js:7:22)
      at Object.<anonymous> (src/fragments/HomePageWelcome/index.js:3:43)
      at Object.<anonymous> (src/fragments/HomePageWelcome/__tests__/HomePageWelcome.test.js:2:50)
      at process._tickCallback (internal/process/next_tick.js:103:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.524s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

```

The test file can be found below:

```javascript
import React from 'react';
import HomePageWelcome from '../../HomePageWelcome'
import renderer from 'react-test-renderer'

test('Home page renders correctly', () => {

  const component = renderer.create(
    <HomePageWelcome
      title={'Espress'}
      video={'https://player.vimeo.com/video/192311619?badge=0&byline=0&portrait=0&title=0&color=388E3C&autoplay=1'}
      cta={ {label: 'Get Started', link: '/register'} }
      hero={'assets/welcome-bg.jpg'} />
  )

  let tree = component.toJSON()

  expect(tree).toMatchSnapshot()

})

```

If anyone can point me in the right direction that would be awesome :)

Thanks!

Strainy

**Comment by MoOx** [comment]
I get this line https://github.com/MoOx/phenomic/blob/4127472c914bb42ae613578c3f166188e118f426/src/components/PageContainer/component.js#L60 is responsible for this problem.
One workaround is to inject an ugly mock that fit the requirement.
Something like 

```js
globals.window = { location: { href: "the right url" } }
```

before the test.

But the component should not break if location is empty and/or href does not exist.

**Comment by Strainy** [comment]
Hey @MoOx, thanks for coming to the rescue again :)

I was able to mock the `Link` component like so:

```javascript
import React from 'react';
import HomePageWelcome from '../../HomePageWelcome'
import renderer from 'react-test-renderer'

jest.mock('phenomic', () => ({
  Link:  'Link',
}))

test('Home page renders correctly', () => {

  const component = renderer.create(
    <HomePageWelcome
      title={'Espress'}
      video={'https://player.vimeo.com/video/192311619?badge=0&byline=0&portrait=0&title=0&color=388E3C&autoplay=1'}
      cta={ {label: 'Get Started', link: '/register'} }
      hero={'assets/welcome-bg.jpg'} />
  )

  let tree = component.toJSON()

  expect(tree).toMatchSnapshot()

})
```

This works well for my purposes.

**Comment by MoOx** [comment]
Closing as it's a bit specific :)
Maybe We will add doc later, after 1.0 refactoring if relevant.

**Comment by MoOx** [comment]
Well actually we can "fix" this.
