### ISSUE TITLE
Unclear Build Errors

### ISSUE THREAD

**Issue by dawidvdh** [MoOx/phenomic#958]
I have been working on a project using phenomic and suddenly I started receiving the errors listed below when running `phenomic build`. However `phenomic start` still works perfectly?

```
✔ Error
    at NormalModule.<anonymous> (/Users/user1/code/project1/front-end/node_modules/webpack-core/lib/NormalModuleMixin.js:79:21)
    at lint (/Users/user1/code/project1/front-end/node_modules/eslint-loader/index.js:113:9)
    at Object.module.exports (/Users/user1/code/project1/front-end/node_modules/eslint-loader/index.js:181:3)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/user1/code/project1/front-end/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/user1/code/project1/front-end/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/user1/code/project1/front-end/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/user1/code/project1/front-end/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/user1/code/project1/front-end/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/user1/code/project1/front-end/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3) +5.53s

✔ Error
    at /Users/user1/code/project1/front-end/node_modules/webpack/lib/Compilation.js:229:38
    at onDoneResolving (/Users/user1/code/project1/front-end/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/user1/code/project1/front-end/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/user1/code/project1/front-end/node_modules/async/lib/async.js:726:13
    at /Users/user1/code/project1/front-end/node_modules/async/lib/async.js:52:16
    at done (/Users/user1/code/project1/front-end/node_modules/async/lib/async.js:241:17)
    at /Users/user1/code/project1/front-end/node_modules/async/lib/async.js:44:16
    at /Users/user1/code/project1/front-end/node_modules/async/lib/async.js:723:17
    at /Users/user1/code/project1/front-end/node_modules/async/lib/async.js:167:37
    at /Users/user1/code/project1/front-end/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/user1/code/project1/front-end/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/user1/code/project1/front-end/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/user1/code/project1/front-end/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/user1/code/project1/front-end/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/user1/code/project1/front-end/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/user1/code/project1/front-end/node_modules/tapable/lib/Tapable.js:134:6
```

Any Guidance on how to solve or even debug these errors would be greatly appreciated.

**Comment by thangngoc89** [comment]
Looks like Phenomic swallows this error. Could you tell me node and npm/yarn version? OS version?

**Comment by dawidvdh** [comment]
Sure thing,

Yarn - v0.20.0
Node - v7.5.0
macOS - 10.12.3 (16D32)

Is there anything else I could provide you with?

**Comment by thangngoc89** [comment]
I'm not a macOS user so I can't help much here. @MoOx  any ideas? 

Normally this is an issue with npm@2 but since you're staying on the edge, I can't tell what is wrong.

**Comment by dawidvdh** [comment]
Hey Found my problem,

After switching to node 4.4.2 it gave me error output. Turns out that for some insane reason i specified the .js extension in the imports of `phenomic.node.js` but after removing them everything works perfectly again.

Thanks for your help

**Comment by thangngoc89** [comment]
I'm glad this worked out for you. But specify `.js` in the import path shouldn't be a problem.

**Comment by HarrisRobin** [comment]
Running into the exact same error.
No clue what's wrong.

Node: 7.40
macOS: 10.12.14

**Comment by MoOx** [comment]
@HarrisRobin is this new? Did you reinstalled node_modules? Switched node version? Do you use phenomic cache option?

**Comment by HarrisRobin** [comment]
@MoOx this is actually from a fresh install. I was attempting to deploy it with netlify-cms and it's failing at the build atm. Not in front of me laptop right now but I'll try a few things like reinstalling node_modules and resetting mom cache. I haven't touched phenomic cache option.

Thanks!

**Comment by xedef** [comment]
Can we reopen this? This is still happening for no apparent reason.
BTW: in my case it works if eslint-loader is disabled from webpack config.

**Comment by MoOx** [comment]
What version are you using? Can you provide your package.json?

**Comment by xedef** [comment]
Hey, @MoOx! I'm using version `0.20.4`.

Here's my package.json:

```JSON
{
  "private": true,
  "name": "xedef-app",
  "twitter": "",
  "repository": "",
  "scripts": {
    "lint:js": "eslint --ignore-path .gitignore --fix .",
    "lint:css": "stylelint \"src/**/*.css\"",
    "lint": "npm-run-all --parallel lint:*",
    "start": "phenomic start",
    "build": "phenomic build",
    "pretest": "npm run lint",
    "clean": "rm -rf ./dist && rm -rf ./node_modules/.cache/babel-loader",
    "test": "npm run build"
  },
  "phenomic": {
    "CNAME": false
  },
  "#babel": "webpack-(development|production) are useful for webpack 2, otherwise use development|production",
  "babel": {
    "env": {
      "test": {
        "presets": [
          "babel-preset-latest",
          "babel-preset-stage-1",
          "babel-preset-react"
        ]
      },
      "development": {
        "presets": [
          "babel-preset-latest",
          "babel-preset-stage-1",
          "babel-preset-react"
        ],
        "plugins": [
          "babel-plugin-transform-react-jsx-source",
          "babel-plugin-transform-react-jsx-self",
          "react-hot-loader/babel"
        ]
      },
      "production": {
        "presets": [
          "babel-preset-react-optimize",
          "babel-preset-latest",
          "babel-preset-stage-1",
          "babel-preset-react"
        ]
      },
      "webpack-development": {
        "presets": [
          [
            "babel-preset-latest",
            {
              "es2015": {
                "modules": false
              }
            }
          ],
          "babel-preset-stage-1",
          "babel-preset-react"
        ],
        "plugins": [
          "babel-plugin-transform-react-jsx-source",
          "babel-plugin-transform-react-jsx-self",
          "react-hot-loader/babel"
        ]
      },
      "webpack-production": {
        "presets": [
          "babel-preset-react-optimize",
          [
            "babel-preset-latest",
            {
              "es2015": {
                "modules": false
              }
            }
          ],
          "babel-preset-stage-1",
          "babel-preset-react"
        ]
      }
    }
  },
  "eslintConfig": {
    "root": true,
    "extends": "./node_modules/phenomic/lib/eslint-config-recommended/index.js"
  },
  "stylelint": {
    "extends": "./node_modules/phenomic/lib/stylelint-config-recommended/index.js"
  },
  "devDependencies": {
    "babel-cli": "^6.14.0",
    "babel-core": "^6.14.0",
    "babel-eslint": "^7.0.0",
    "babel-loader": "^6.2.5",
    "babel-plugin-transform-react-jsx-self": "^6.11.0",
    "babel-plugin-transform-react-jsx-source": "^6.9.0",
    "babel-preset-latest": "^6.14.0",
    "babel-preset-react": "^6.3.13",
    "babel-preset-react-optimize": "^1.0.1",
    "babel-preset-stage-1": "^6.13.0",
    "classnames": "^2.2.5",
    "css-loader": "^0.25.0",
    "eslint": "^3.7.1",
    "eslint-loader": "^1.5.0",
    "eslint-plugin-react": "^6.4.0",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "history": "^2.0.0",
    "json-loader": "^0.5.2",
    "npm-run-all": "^1.7.0",
    "phenomic": "^0.20.4",
    "postcss-browser-reporter": "^0.4.0",
    "postcss-cssnext": "^2.4.0",
    "postcss-loader": "^0.13.0",
    "postcss-reporter": "^1.3.0",
    "raw-loader": "^0.5.1",
    "react": "^15.0.0-rc.1",
    "react-dom": "^15.0.0-rc.1",
    "react-helmet": "^3.0.0",
    "react-hot-loader": "^3.0.0-beta",
    "react-redux": "^4.0.0",
    "react-router": "^2.3.0",
    "react-svg-inline": "^1.1.0",
    "react-topbar-progress-indicator": "^1.0.0",
    "redux": "^3.0.0",
    "style-loader": "^0.13.0",
    "stylelint": "^7.2.0",
    "warning": "^3.0.0",
    "webpack": "^1.11.0",
    "whatwg-fetch": "^0.11.0"
  },
  "dependencies": {
    "react-flexbox-grid": "^1.0.2",
    "react-imation": "^0.5.3",
    "react-scroll": "^1.4.7",
    "react-slick": "^0.14.7",
    "react-track": "^0.4.3",
    "react-waypoint": "^5.2.0",
    "slick-carousel": "^1.6.0"
  }
}
```

**Comment by MoOx** [comment]
Can you try updating eslint-loader to latest version?
