### ISSUE TITLE
I'm not able to use firebase with phenomic

### ISSUE THREAD

**Issue by alexzaporozhets** [MoOx/phenomic#966]
**npm run build**
```node_modules/firebase/messaging.js:38
}).call(typeof global !== undefined ? global : typeof self !== undefined ? self : typeof window !== undefined ? window : {});
 ^
ReferenceError: 

self is not defined

    at node_modules/firebase/messaging.js:25:361
    at node_modules/firebase/messaging.js:37:612
    at Object.module.exports.module.exports (node_modules/firebase/messaging.js:38:2)
    at __webpack_require__ (webpack:/webpack/bootstrap e1f05db17a810fb79946:19:1)
    at Object.module.exports.firebase (node_modules/firebase/firebase-browser.js:12:1)
    at __webpack_require__ (webpack:/webpack/bootstrap e1f05db17a810fb79946:19:1)
    at Object.<anonymous> (webpack:/src/components/forms/BaseMessageForm.js:2:1)
    at __webpack_require__ (webpack:/webpack/bootstrap e1f05db17a810fb79946:19:1)
    at Object.module.exports.Object.defineProperty.value (webpack:/src/components/forms/CallbackForm.js:2:1)
    at __webpack_require__ (webpack:/webpack/bootstrap e1f05db17a810fb79946:19:1)
    at Object.module.exports.Object.defineProperty.value (webpack:/src/components/Footer/index.js:3:1)
    at __webpack_require__ (webpack:/webpack/bootstrap e1f05db17a810fb79946:19:1)
    at Object.module.exports.Object.defineProperty.value (webpack:/src/AppContainer.js:7:1)
    at __webpack_require__ (webpack:/webpack/bootstrap e1f05db17a810fb79946:19:1)
    at Object.module.exports.Object.defineProperty.value (webpack:/src/routes.js:5:1)
    at __webpack_require__ (webpack:/webpack/bootstrap e1f05db17a810fb79946:19:1)

If you are seeing this message during the static build, that means you areprobably using an API only available in the browser (such as 'window', 'document', 'Element'...). Note that a module can be responsible for this.
In order to prevent this error, you can simply avoid calling the code responsible when the dependency is not available. 

Examples:

For a single API:

  const element = (typeof document !== "undefined") ? document.querySelector(".something") : null

  if (element) {
    // do your thing with your element
  }

For a module:

  const clipboard = (typeof window !== "undefined") ? require("clipboard") : null

  // then later

  if (clipboard) {
    // do your thing using the module
  }
```

**Comment by montogeek** [comment]
Are you using `fetch`?

**Comment by montogeek** [comment]
Sorry, `self` exists in `window` object, since bundling happens in a Node environment you should call firebase functions only on a browser environment, like this:
```js
const isClient = typeof window !== "undefined"
if(isClient) {
 // firebase code
}
```

**Comment by alexzaporozhets** [comment]
@montogeek ```import * as firebase from "firebase";```

**Comment by alexzaporozhets** [comment]
I found a workaround with require().
```
const isClient = typeof window !== "undefined";

if (isClient) {
  const firebase = require('firebase');

  // Initialize Firebase
  const config = {
    apiKey: ...,
    authDomain: ...,
    databaseURL: ...,
    storageBucket: ...,
    messagingSenderId: ...
  };
  firebase.initializeApp(config);
}
```

**Comment by montogeek** [comment]
Yes, that is the accepted solution

**Comment by MoOx** [comment]
The workaround is explained in the long error message you got in the first place...
