### ISSUE TITLE
Module build failed: DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic

### ISSUE THREAD

**Issue by SastraNababan** [MoOx/phenomic#984]
Everytime I run `phenomic start` I got this error 
(http://pastebin.com/YKjtrcDb)

```
⠙ Updating(node:8404) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
✖ Updated with warnings

⚠ Warning in ./content/404.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more information, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:88:11)
 @ ./content \.(md|markdown)$
 @ ./scripts/phenomic.browser.js
 @ multi /usr/local/lib/~/phenomic/~/webpack-hot-middleware/client.js ./scripts/phenomic.browser.js

⚠ Warning in ./content/about.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more information, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:88:11)
 @ ./content \.(md|markdown)$
 @ ./scripts/phenomic.browser.js
 @ multi /usr/local/lib/~/phenomic/~/webpack-hot-middleware/client.js ./scripts/phenomic.browser.js

⚠ Warning in ./content/index.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more information, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:88:11)
 @ ./content \.(md|markdown)$
 @ ./scripts/phenomic.browser.js
 @ multi /usr/local/lib/~/phenomic/~/webpack-hot-middleware/client.js ./scripts/phenomic.browser.js

⚠ Warning in ./content/posts/first-post.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more information, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:88:11)
 @ ./content \.(md|markdown)$
 @ ./scripts/phenomic.browser.js
 @ multi /usr/local/lib/~/phenomic/~/webpack-hot-middleware/client.js ./scripts/phenomic.browser.js

⚠ Warning in ./content/posts/hello-world.md
Module build failed: Error: You are using phenomic loader without the corresponding plugin. This plugin should be added automatically by Phenomic, so if you are facing this issue, you are probably playing with the fire. To get more information, you can reach us on our community chat. https://phenomic.io/
    at Object.loader (./node_modules/phenomic/lib/loader/index.js:88:11)
 @ ./content \.(md|markdown)$
 @ ./scripts/phenomic.browser.js
 @ multi /usr/local/lib/~/phenomic/~/webpack-hot-middleware/client.js ./scripts/phenomic.browser.js
```
Here's my [webpack config ](http://pastebin.com/mBcTR0LA) and [package.json](http://pastebin.com/YKjtrcDb)

**Comment by MoOx** [comment]
Thanks for reporting. It's probably due to latest update from webpack 😭.
Will try to fix asap. A workaround is to use webpack 2.2.0 :)

**Comment by MoOx** [comment]
I am on it.
