### ISSUE TITLE
ServerSideStyles not working with webpack 2

### ISSUE THREAD

**Issue by jesnil01** [MoOx/phenomic#986]
Can't get styled-components to render on the server with ServerSideStyles.js mentioned in the docs. Have tried with multiple versions of webpack and styled-components.

I use these versions: 
webpack 2.2.1
styled-components 1.4.4

Get this message in console when running `npm run build`:

`node_modules/styled-components/lib/vendor/glamor/sheet.js:196
        return this.sheet.cssRules;
^
TypeError: 

Cannot read property 'cssRules' of undefined

    at StyleSheet.rules (node_modules/styled-components/lib/vendor/glamor/sheet.js:196:1)
    at StyleSheet.rules (node_modules/styled-components/lib/models/StyleSheet.js:54:1)
    at ServerSideStyles (webpack:/src/components/ServerSideStyles.js:7:29)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (node_modules/react-dom/lib/ReactCompositeComponent.js:309:1)
    at ReactCompositeComponentWrapper._constructComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:285:1)
    at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:188:1)
    at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:1)
    at ReactDOMComponent.mountChildren (node_modules/react-dom/lib/ReactMultiChild.js:238:1)
    at ReactDOMComponent._createContentMarkup (node_modules/react-dom/lib/ReactDOMComponent.js:653:1)
    at ReactDOMComponent.mountComponent (node_modules/react-dom/lib/ReactDOMComponent.js:520:1)
    at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:1)
    at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:1)
    at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:1)
    at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:1)
    at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:1)
    at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:1)
error Command failed with exit code 1.`

Any clues?

**Comment by MoOx** [comment]
poke @raygesualdo (I never used styled-components yet)

**Comment by raygesualdo** [comment]
Hey @jesnil01, is the code you're working on public? Or can you provide code snippets of your implementation?

**Comment by montogeek** [comment]
@mxstbr Do you maybe have an idea about this?

**Comment by jesnil01** [comment]
@raygesualdo Unfortunatly it's not public but I stripped some code for debugging purposes and published here: https://github.com/jesnil01/phenomic-styled-components

Any thoughts? :)

**Comment by raygesualdo** [comment]
Alright @jesnil01, it took a bit but I figured it out 😃 Based on [this SSR thread](https://github.com/styled-components/styled-components/issues/124#issuecomment-259300374), I added an entry to the `resolve` section of your webpack config. Here is what the resolve section should look like:

```javascript
resolve: { 
  extensions: [ ".js", ".json" ], 
  alias: { "styled-components": "styled-components/lib" }
}
```

Give that a shot and let me know!

**Comment by raygesualdo** [comment]
Keep in mind that all of this will be much simpler with the imminent release of styled-components v2. An API was added to streamline the SSR process.

**Comment by jesnil01** [comment]
@raygesualdo That seems to work. Big thumbs up to you!

**Comment by MoOx** [comment]
So is our doc incorrect?

**Comment by raygesualdo** [comment]
The docs are technically correct. There is a bug with SSR, styled-components and webpack v2 that could be more thoroughly documented. I can put together a PR today/tomorrow to get the note added in.

**Comment by raygesualdo** [comment]
Additionally, when styled-components v2 comes out, I'm going to PR an SSR integration (similar to Aphrodite and Glamor) such that manual steps - and this bug - are obsolete.
